version: 2.1

orbs:
  # node: circleci/node@4.4.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

# jobs:
#   build:
#     executor: node/default
#     steps:
#       - checkout
#       - setup_remote_docker
#       - node/install-packages
#       - run: npm run build

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          executor:
            image: default
          filters:
            tags:
              only: /^v.*/
          repo: 'hills-carpal-repo'
          tag: '${CIRCLE_SHA1}'

      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only:
                - master
          requires:
            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
          family: 'hills-carpal-task-training'
          cluster-name: 'hills-carpal-cluster-training'
          container-image-name-updates: 'container=hills-carpal-task-training,tag=${CIRCLE_SHA1}'
          service-name: 'hills-carpal-service-training'

      - aws-ecs/deploy-service-update:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
          family: 'hills-carpal-task-prod'
          cluster-name: 'hills-carpal-cluster-prod'
          container-image-name-updates: 'container=hills-carpal-task-prod,tag=${CIRCLE_SHA1}'
          service-name: 'hills-carpal-service-prod'
