version: 2.1

orbs:
  # node: circleci/node@4.4.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

# jobs:
#   build:
#     executor: node/default
#     steps:
#       - checkout
#       - setup_remote_docker
#       - node/install-packages
#       - run: npm run build

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "201335468138.dkr.ecr.ap-southeast-2.amazonaws.com/hills-carpal-repo"
          tag: "${CIRCLE_SHA1}"
          account-url: 201335468138.dkr.ecr.ap-southeast-2.amazonaws.com
          region: ap-southeast-2

      # - aws-ecs/deploy-service-update:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
      #     family: "hills-carpal-service-training"
      #     cluster-name: "hills-carpal-cluster-training"
      #     container-image-name-updates: "container=hills-carpal-service-training,tag=${CIRCLE_SHA1}"

      # - aws-ecs/deploy-service-update:
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
      #     family: "hills-carpal-service-production"
      #     cluster-name: "hills-carpal-cluster-production"
      #     container-image-name-updates: "container=hills-carpal-service-production,tag=${CIRCLE_SHA1}"



